  customer-service:
    build: ./customer-service
    ports:
      - "8083:8083"
    depends_on:
      - customer-mongo

  customer-mongo:
    image: mongo:6
    container_name: customer-mongo
    ports:
      - "27019:27017"
