version: '3'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    command: mongod --noauth  # Tắt xác thực MongoDB

  mongo-express:
    image: mongo-express
    ports:
      - "8082:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_BASICAUTH: "false"  # Tắt xác thực UI mongo-express
