services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

  api-gateway:
    build: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - product-service
      - order-service
      - customer-service
      - payment-service
      - inventory-service
      - shipping-service

  product-service:
    build: ./product-service
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/productdb
    depends_on:
      - mongo

  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/orderdb
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  customer-service:
    build: ./customer-service
    ports:
      - "8083:8083"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/customerdb
    depends_on:
      - mongo

  payment-service:
    build: ./payment-service
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/paymentdb
    depends_on:
      - mongo

  inventory-service:
    build: ./inventory-service
    ports:
      - "8085:8085"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/inventorydb
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mongo
      - rabbitmq

  shipping-service:
    build: ./shipping-service
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/shippingdb
      - SPRING_RABBITMQ_HOST=rabbitmq
    depends_on:
      - mongo
      - rabbitmq

networks:
  default:
    name: microservices-network
