  order-service:
    build: ./order-service
    ports:
      - "8082:8082"
    depends_on:
      - order-mongo

  order-mongo:
    image: mongo:6
    container_name: order-mongo
    ports:
      - "27018:27017"
