# Sử dụng Nginx làm base image
FROM nginx:latest

# Sao chép file index.html vào thư mục mặc định của Nginx
COPY index.html /usr/share/nginx/html/index.html

# Mở cổng 80 để phục vụ trang web
EXPOSE 80
