spring:
  data:
    mongodb:
      host: localhost
      port: 27018
      database: orderdb
  application:
    name: order-service

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest


server:
  port: 8082
